pwittchen/NetworkEvents

network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkState.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/Ping.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/BaseBroadcastReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiver.java
=> Fixing bug with pushing ConnectivityChanged event twice to the bus

.idea/misc.xml, gradle.properties, maven_push.gradle, network-events-library/build.gradle, network-events-library/gradle.properties
=> preparing for release

.idea/misc.xml, gradle.properties, maven_push.gradle, network-events-library/build.gradle, network-events-library/gradle.properties
=> Preparing for release on development branch

README.md
=> adding download section to README.md file

.travis.yml, build.gradle, example/build.gradle, example/example.iml, example/src/main/res/values/strings.xml, example/src/main/res/values/styles.xml, network-events-library/build.gradle, network-events-library/network-events-library.iml, network-events-library/src/main/AndroidManifest.xml, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/ConnectivityStatus.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkHelper.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkState.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/Ping.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/event/ConnectivityChanged.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/event/WifiSignalStrengthChanged.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/BaseBroadcastReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiver.java
=> updates for milestone 1.0.1

gradle.properties
=> prepare for release version 1.0.1

README.md
=> updating app version and min sdk in README.md file

README.md
=> updating library version in README.md file

.travis.yml, README.md, build.gradle, example-dagger/example-dagger.iml, example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/AndroidModule.java, example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/BaseApplication.java, example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/MainActivity.java, example/example.iml, example/src/main/java/com/github/pwittchen/networkevents/app/MainActivity.java, network-events-library/network-events-library.iml, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/TestUtils.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiverTest.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkHelper.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/Ping.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/Task.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/BaseBroadcastReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiver.java
Solves #30.
* refactored project
* added unit tests
* added missing comments with license
* updated `README.md` file
* updated Android Build Tools to 1.1.0
* updated `.travis.yml` file
* public API remains the same as before
=> project refactoring and adding unit tests

gradle.properties
=> prepare for release of v. 1.0.3

.idea/gradle.xml, NetworkEvents.iml, example-dagger/example-dagger.iml, example/example.iml, network-events-library/build.gradle, network-events-library/network-events-library.iml, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiverTest.java
=> migrating unit tests to AndroidJunit4 runner and Google Truth

example-dagger/example-dagger.iml, example/example.iml, network-events-library/build.gradle, network-events-library/network-events-library.iml, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiverTest.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/Ping.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java
Fixing spelling mistake, adding mockito and small code refactoring.
=> updating Unit Tests

gradle.properties
=> updating version of the library to 1.0.4

gradle.properties
=> updating library version to 1.0.5

example-disabling-ping-and-wifi-scan/src/main/java/com/github/pwittchen/networkevents/app/disablingpingandwifiscan/MainActivity.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java
=> disabling wifi access points scan by default and updating API

example-dagger/src/main/AndroidManifest.xml, example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/AndroidModule.java, example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/BaseActivity.java, example-dagger/src/main/res/values/styles.xml, example-greenrobot-bus/src/main/AndroidManifest.xml, example/src/main/AndroidManifest.xml, example/src/main/java/com/github/pwittchen/networkevents/app/MainActivity.java, example/src/main/res/values/styles.xml, network-events-library/src/main/AndroidManifest.xml
=> moving permissions to Manifest of library

example-dagger/src/main/java/com/github/pwittchen/networkevents/dagger/app/MainActivity.java, example-dagger/src/main/res/layout/activity_main.xml, example-dagger/src/main/res/values/strings.xml, example-greenrobot-bus/src/main/java/com/github/pwittchen/networkevents/greenrobot/app/MainActivity.java, example-greenrobot-bus/src/main/res/layout/activity_main.xml, example-greenrobot-bus/src/main/res/values/strings.xml, example/src/main/java/com/github/pwittchen/networkevents/app/MainActivity.java, example/src/main/res/layout/activity_main.xml, example/src/main/res/values/strings.xml, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiverTest.java, network-events-library/src/androidTest/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiverTest.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/MobileNetworkType.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/event/ConnectivityChanged.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/event/WifiSignalStrengthChanged.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/BaseBroadcastReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/WifiSignalStrengthChangeReceiver.java
=> add possibility to get mobile network type in ConnectivityChanged event

gradle.properties
=> bumping version to 2.0.0

README.md, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/BaseBroadcastReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/InternetConnectionChangeReceiver.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java
=> disabling WIFI_CONNECTED status when enableInternetCheck() method is called

.travis.yml, build.gradle, example-dagger/build.gradle, example-greenrobot-bus/build.gradle, example/build.gradle, network-events-library/build.gradle
=> bump target sdk and build tools version

gradle.properties
=> bump library version to 2.1.2

example-greenrobot-bus/build.gradle, example-greenrobot-bus/src/main/java/com/github/pwittchen/networkevents/greenrobot/app/MainActivity.java
Without @Subsribe annotation it through the following RuntimeException: 
org.greenrobot.eventbus.EventBusException: Subscriber class and its super classes have no public methods with the @Subscribe annotation
=> Update green robot

example-greenrobot-bus/src/main/java/com/github/pwittchen/networkevents/greenrobot/app/MainActivity.java, example/src/main/java/com/github/pwittchen/networkevents/app/MainActivity.java, network-events-library/src/main/AndroidManifest.xml, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/internet/OnlineCheckerImpl.java
=> changing implementation of the OnlineChecker

network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkHelper.java
=> restoring NetworkHelper with one method

README.md, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/internet/OnlineChecker.java, network-events-library/src/main/java/com/github/pwittchen/networkevents/library/internet/OnlineCheckerImpl.java
=> adding ping customization
